branch-defaults:
  default:
    environment: tapalong-dev
global:
  application_name: tapalong
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
